
local_resource ('test build',
  'timeout 120 go run .. up bash build.sh',
  deps=['..'],
  labels=["tests"],
)

local_resource ('test pull tag inspect delete',
  'timeout 200 go run .. up bash pull-tag-inspect-delete.sh',
  deps=['..'],
  labels=["tests"],
)
