
local_resource ('test build',
  'timeout 120 bash build.sh',
  deps=['..'],
  labels=["tests"],
)

local_resource ('test pull tag',
  'timeout 200 bash docker-pull-tag-push.sh',
  deps=['..'],
  labels=["tests"],
)

local_resource ('test inspect',
  'timeout 200 bash docker-inspect.sh',
  deps=['..'],
  labels=["tests"],
)
