
local_resource ('test docker build',
  'time timeout 60 bash docker-build.sh',
  deps=['..'],
  resource_deps=['wedding'],
  allow_parallel=True,
)

local_resource ('test docker pull tag push',
  'time timeout 60 bash docker-pull-tag-push.sh',
  deps=['..'],
  resource_deps=['wedding'],
  allow_parallel=True,
)

local_resource ('test tilt ci',
  'time timeout 180 bash tilt-ci.sh',
  deps=['..'],
  resource_deps=['wedding'],
  allow_parallel=True,
)
