apiVersion: v1
kind: Service
metadata:
  name: d8s-dind
spec:
  ports:
    - name: dind
      port: 2375
  selector:
    app: d8s-dind
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d8s-dind
spec:
  selector:
    matchLabels:
      app: d8s-dind
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: d8s-dind
    spec:
      containers:
        - name: dind
          image: docker:20.10.11-dind
          args:
            - --tls=false
            - --insecure-registry=d8s-registry:5000
            - --mtu=1300
            - --registry-mirror=http://d8s-docker-hub-mirror:5000
            - --insecure-registry=d8s-docker-hub-mirror:5000
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
            - name: DOCKER_BUILDKIT
              value: "1"
          securityContext: 
            privileged: true
          ports:
            - name: http
              containerPort: 2375
          resources:
            limits:
              cpu: "1000m"
              memory: "8Gi"
            requests:
              cpu: "100m"
              memory: "8Gi"
          readinessProbe:
            httpGet:
              path: /_ping
              port: 2375
          volumeMounts:
            - name: data
              mountPath: /var/lib/docker 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: d8s-dind
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d8s-dind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
