apiVersion: v1
kind: Service
metadata:
  name: d8s-docker-hub-mirror
spec:
  ports:
    - name: http
      port: 5000
  selector:
    app: d8s-docker-hub-mirror
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d8s-docker-hub-mirror
spec:
  selector:
    matchLabels:
      app: d8s-docker-hub-mirror
  replicas: 1
  template:
    metadata:
      labels:
        app: d8s-docker-hub-mirror
    spec:
      containers:
        - name: d8s-docker-hub-mirror
          image: registry:2.7.1
          ports:
            - name: http
              containerPort: 5000
          resources:
            limits:
              cpu: 1000m
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
          readinessProbe:
            httpGet:
              path: /v2/_catalog?n=1
              port: 5000
          env:
            - name: REGISTRY_LOG_ACCESSLOG_DISABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: "warn"
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: d8s-minio
                  key: MINIO_ACCESS_KEY
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: d8s-minio
                  key: MINIO_SECRET_KEY
            - name: REGISTRY_HTTP_SECRET
              value: abc123
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry/
      volumes:
        - name: config
          configMap:
            name: d8s-docker-hub-mirror
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: d8s-docker-hub-mirror
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry-mirror
    storage:
      s3:
        region: us-east-1
        regionendpoint: http://d8s-minio:9000
        bucket: docker-hub-mirror
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
      redirect:
        disable: true
    proxy:
      remoteurl: https://registry-1.docker.io
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
