apiVersion: v1
kind: Service
metadata:
  name: wedding-minio
spec:
  ports:
    - name: minio
      port: 9000
  selector:
    app: wedding-minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-minio
spec:
  selector:
    matchLabels:
      app: wedding-minio
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: wedding-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-12-29T23-29-29Z
          args:
            - server
            - /home/shared
          envFrom:
            - secretRef:
                name: wedding-minio
          ports:
            - name: http
              containerPort: 9000
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
          volumeMounts:
            - name: data
              mountPath: /home/shared
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wedding-minio
---
apiVersion: v1
kind: Secret
metadata:
  name: wedding-minio
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minio123
  MINIO_SECRET_KEY: minio456
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wedding-minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-minio-buckets
spec:
  backoffLimit: 20
  template:
    metadata:
      name: setup-minio-bucket
    spec:
      containers:
        - name: mc
          image: minio/mc:RELEASE.2020-12-18T10-53-53Z
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://wedding-minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc mb minio/contexts --ignore-existing
              mc mb minio/registry --ignore-existing
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: minio
          secret:
            secretName: wedding-minio
      restartPolicy: OnFailure
