apiVersion: batch/v1
kind: Job
metadata:
  name: setup-s3-bucket
spec:
  backoffLimit: 20
  template:
    metadata:
      name: setup-s3-bucket
    spec:
      containers:
        - name: mc
          image: minio/mc:RELEASE.2020-05-16T01-44-37Z
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc mb minio/wedding --ignore-existing
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: minio
          secret:
            secretName: minio
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-old-files
spec:
  backoffLimit: 20
  template:
    metadata:
      name: delete-old-files
    spec:
      containers:
        - name: mc
          image: minio/mc:RELEASE.2020-05-16T01-44-37Z
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc rm -r --older-than 2h --force minio/wedding
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: minio
          secret:
            secretName: minio
      restartPolicy: OnFailure