apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: minio
      port: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
        app: minio
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-05-16T01-33-21Z
          args:
            - server
            - /home/shared
          envFrom:
            - secretRef:
                name: minio
          ports:
            - name: http
              containerPort: 9000
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
          volumeMounts:
            - name: data
              mountPath: /home/shared
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minio123
  MINIO_SECRET_KEY: minio456
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
