apiVersion: v1
kind: Service
metadata:
  name: wedding-registry
spec:
  ports:
    - name: http
      port: 5000
  selector:
    app: wedding-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-registry
spec:
  selector:
    matchLabels:
      app: wedding-registry
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: wedding-registry
    spec:
      containers:
        - name: wedding-registry
          image: registry:2.7.1
          ports:
            - name: http
              containerPort: 5000
          resources:
            limits:
              cpu: 1000m
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /debug/health
              port: 5001
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
          env:
            - name: REGISTRY_LOG_ACCESSLOG_DISABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: "warn"
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: wedding-minio
                  key: MINIO_ACCESS_KEY
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: wedding-minio
                  key: MINIO_SECRET_KEY
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: wedding-registry
                  key: HTTP_SECRET
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry/
      volumes:
        - name: config
          configMap:
            name: wedding-registry
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - wedding-registry
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: registry
  namespace: registry
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: registry
      readonly: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: wedding-registry
type: Opaque
stringData:
  HTTP_SECRET: shared_secret_123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wedding-registry
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      s3:
        region: us-east-1
        regionendpoint: http://wedding-minio:9000
        bucket: registry
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
      delete:
        enabled: true
      maintenance:
        uploadpurging:
          enabled: false
        readonly:
          enabled: false
      redirect:
        disable: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      debug:
        addr: :5001
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
