k8s_yaml('minio.yaml')
k8s_resource(
  'wedding-minio',
  new_name='minio',
  port_forwards=9000,
)
k8s_resource(
  'setup-minio-buckets',
  new_name='minio-buckets',
  resource_deps=['minio'],
)

k8s_yaml('registry.yaml')
k8s_resource(
  'wedding-registry',
  new_name='registry',
  port_forwards=5000,
)
