apiVersion: v1
kind: Service
metadata:
  name: wedding-registry
spec:
  ports:
    - name: http
      port: 5000
  selector:
    app: wedding-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-registry
spec:
  selector:
    matchLabels:
        app: wedding-registry
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: wedding-registry
    spec:
      containers:
        - name: wedding-registry
          image: registry:2.7.1
          ports:
            - name: http
              containerPort: 5000
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
          env:
            - name: REGISTRY_LOG_ACCESSLOG_DISABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: "warn"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wedding-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wedding-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
