disable_snapshots()
allow_k8s_contexts(['test', 'ci'])

load('ext://min_tilt_version', 'min_tilt_version')
min_tilt_version('0.15.0') # includes fix for auto_init+False with tilt ci

k8s_yaml('kubernetes.yaml')

default_registry('registry.registry.svc:5000')

docker_build('service-a-image', './image-a')
docker_build('service-b-image', './image-b')
