disable_snapshots()
allow_k8s_contexts(['test', 'ci'])

load('ext://min_tilt_version', 'min_tilt_version')
min_tilt_version('0.15.0') # includes fix for auto_init+False with tilt ci

k8s_yaml('kubernetes.yaml')

docker_build('service-a-image', './image-a', build_args={'ECHO': 'a'})
docker_build('service-b-image', './image-b', target='http')

k8s_yaml('verify-a.yaml')
k8s_yaml('verify-b.yaml')

k8s_resource('verify-a', resource_deps=['service-a'])
k8s_resource('verify-b', resource_deps=['service-b'])
