k8s_yaml('minio.yaml')
k8s_resource('minio', port_forwards=9000)

k8s_yaml('minio-setup.yaml')
k8s_resource(
  'setup-s3-bucket',
  resource_deps=['minio'],
)
k8s_resource(
  'delete-old-files',
  resource_deps=['setup-s3-bucket'],
)

k8s_yaml('cache-registry.yaml')
k8s_resource('cache-registry', port_forwards=5000)
