apiVersion: v1
kind: Service
metadata:
  name: dinner
spec:
  selector:
    app: dinner
  ports:
    - name: dinner
      port: 2375
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner
  labels:
    app: dinner
spec:
  selector:
    matchLabels:
      app: dinner
  template:
    metadata:
      labels:
        app: dinner
    spec:
      containers:
        - name: dinner
          image: davedamoon/dinner:latest
          args:
            - --s3-endpoint=d8s-minio:9000
            - --s3-access-key-file=/secret/minio/MINIO_ACCESS_KEY
            - --s3-secret-key-file=/secret/minio/MINIO_SECRET_KEY
            - --s3-ssl=false
            - --s3-bucket=chunks
            - --upstream=http://d8s-dind:2375
          ports:
            - name: dinner
              containerPort: 2375
          readinessProbe:
            httpGet:
              path: /_ping
              port: 2375
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
          resources:
            requests:
              memory: "1Gi" # increased to allow go to compile, and tilt to hot reload
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "200m"
      volumes:
        - name: minio
          secret:
            secretName: d8s-minio
