apiVersion: v1
kind: Service
metadata:
  name: dinner
spec:
  selector:
    app: dinner
  ports:
    - name: dinner
      port: 2376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner
  labels:
    app: dinner
spec:
  selector:
    matchLabels:
      app: dinner
  template:
    metadata:
      labels:
        app: dinner
    spec:
      serviceAccountName: dinner
      containers:
        - name: dinner
          image: davedamoon/dinner:latest
          ports:
            - name: dinner
              containerPort: 2376
          readinessProbe:
            httpGet:
              path: /_ping
              port: 2376
          resources:
            requests:
              memory: "1Gi" # increased to allow go to compile, and tilt to hot reload
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "200m"
